### PR TITLE
Make histogram cumulative

### PR DESCRIPTION
**Pull request by lorenz**
ebpf_exporter currently does not conform to Prometheus's histogram specifications because its buckets are not cumulative (higher buckets don't contain lower ones). This causes issues when using Prometheus histogram processing functions and Grafana's heatmap visualization. This PR fixes that and makes the buckets cumulative.

### CODE REVIEW

**Comment by dswarbrick** [comment]
I'm not sure I follow. The values are already cumulative (they are never reset). Perhaps you mean _contiguous_ buckets, i.e., all buckets present from the start, with no gaps in them. Is that what is causing the issue with Grafana?

**Comment by dswarbrick** [comment]
Ah, ok now I understand. I was not aware that Prometheus histograms are cumulative (unlike the BPF histograms). Brian Brazil explains it well at https://www.robustperception.io/why-are-prometheus-histograms-cumulative/

**Comment by lorenz** [comment]
Yeah, I should've linked to some documentation of what it's doing. I even thought of linking that blog post but I forgot.

I also removed my Kubernetes spec file (was an artifact from an interactive rebase from an internal repo) since it has nothing to do with this PR.

I also quickly took this screenshot of the final thing, looks pretty cool (sda is a SLOG, so no reads):
grafana-ebpf-heatmap

**Comment by dswarbrick** [comment]
@lorenz I refactored my code fairly heavily, so that the parsed values are written to an order-preserving array, and then summed later when passing the bucket map to `MustNewConstHistogram()`.

I've also ensured that all buckets are exposed, as I found that Grafana's stacked bar chart was showing bogus negative values when the buckets had gaps in the sequence. This should resolve the problems you experienced with it. If you like, you can try experimenting with adding a test for non-zero `v` around the line `promBuckets[math.Exp2(float64(k))] = count` to omit buckets where the BPF histogram bucket was zero.

**Pull request closed without merging**
